// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnlterelwwnkxuhumuki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhubHRlcmVsd3dua3h1aHVtdWtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDM5NzksImV4cCI6MjA3MTE3OTk3OX0.-rMkjjEuNLu8BP6r0lR7HHfAYuuTMrgz1aJ3QD0VlXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});